### ISSUE TITLE
what's next for @bentley/react-scripts ?

### ISSUE THREAD

**Issue by lijiayi0921** [imodeljs/create-react-app#115]
Hello,

react-scripts seems to be abandonned since 2 years.
https://www.npmjs.com/package/react-scripts
Also create react app seems to have been removed from the official workflow
https://react.dev/learn/start-a-new-react-project

I wanted to know what would be the future of @bentley/react-scripts ?

Currently having iTwinjs integrated in the frontend of our application, we are kind of dependent on @bentley/react-scripts.
It appears sooner or later we'll need to switch to something else.
Is something being planned for @bentley/react-scripts ?

Thank you
Jiayi

**Comment by aruniverse** [comment]
Hi,

As you have noticed the JavaScript (and more specifically the React) Community at large has been moving away from react-scripts. We are looking to switch to [Vite](https://vitejs.dev/).

We have already transitioned the test-apps within the [itwinjs-core repo](https://github.com/iTwin/itwinjs-core/blob/master/test-apps) from react-scripts to [vite](https://github.com/iTwin/itwinjs-core/blob/master/test-apps/display-test-app/vite.config.ts). 

We are investigating if we need to make an additional pkg to publish a default itwin vite config, but so far vite has been proven to be successful with our usage.

**Comment by lijiayi0921** [comment]
Thanks @aruniverse for your response.
We are also considering moving to Vite, so good news for us :)
I'll do the move based on the test project.
Regards,
Jiayi
