### ISSUE TITLE
webpack-dev-server version needs bump

### ISSUE THREAD

**Issue by blackandwhitezephyr** [imodeljs/create-react-app#74]
webpack-dev-server 3.x depends on selfsigned 1.x, which depends on node-forge^0.10.0, which has security vulnerabilities.
See the fix for selfsigned: https://github.com/jfromaniello/selfsigned/issues/55 
Need top bump the webpack-dev-server version to get the fixed version of selfsigned.

**Comment by aruniverse** [comment]
Please take a look at this discussion thread regarding security vulnerabilities on our fork here: https://github.com/iTwin/itwinjs-core/discussions/3397

https://twitter.com/dan_abramov/status/1412376404738686984

**Comment by blackandwhitezephyr** [comment]
Thank you @aruniverse. Closing this.
