### ISSUE TITLE
"BREAKING CHANGE: webpack < 5 used" warning with @bentley/react-scripts 5

### ISSUE THREAD

**Issue by lijiayi0921** [imodeljs/create-react-app#87]
Hi,

I upgraded @bentley/react-scripts to version 5 of my application.
Now I'm having those warnings while launching my react app : 

```
WARNING in ./node_modules/@itwin/core-common/lib/esm/rpc/web/WebAppRpcLogging.js 18:23-36
Module not found: Error: Can't resolve 'os' in 'C:\xxxxx\node_modules\@itwin\core-common\lib\esm\rpc\web

BREAKING CHANGE: webpack < 5 used to include polyfills for node.js core modules by default.
This is no longer the case. Verify if you need this module and configure a polyfill for it.`
```

```

WARNING in ./node_modules/sax/lib/sax.js 163:13-37
Module not found: Error: Can't resolve 'stream' in 'C:\xxxxx\node_modules\sax\lib'

BREAKING CHANGE: webpack < 5 used to include polyfills for node.js core modules by default.
This is no longer the case. Verify if you need this module and configure a polyfill for it.
```

The react app launches normally as it seems.

The same can be reproduced by simply upgrading @bentley/react-scripts in the newly created itwin create app (@bentley/react-scripts 5.0.2)

`npx create-react-app your-app-name --template @itwin/web-viewer --scripts-version @bentley/react-scripts`

1. Is that something I need to worry about ? 
2. If so, how do I fix it ?
3. Should I put @bentley/react-scripts as dependency or devDependency ?

Many thanks
Jiayi

**Comment by aruniverse** [comment]
Hi,

> 1. Is that something I need to worry about ?

No, these are warnings that you should be able to ignore. We will have this partially fixed in iTwin.js 3.5, specifically the warnings coming from `node_modules/@itwin`

> 2. If so, how do I fix it ?

If the warning is really bothering you, you could eject from react-scripts and add the polyfill back in yourself

> 3. Should I put @bentley/react-scripts as dependency or devDependency ?

It should be a devDependency

**Comment by lijiayi0921** [comment]
Thanks @aruniverse for you fast response !
I'll simply ignore the warnings.
Cheers
Jiayi
